'use client';

import React from 'react';
import './globals.css';
// eslint-disable-next-line import/no-extraneous-dependencies
import { ChakraProvider } from '@chakra-ui/react';
// eslint-disable-next-line import/no-extraneous-dependencies
import { CacheProvider } from '@chakra-ui/next-js';

export const metadata = {
  title: 'Austins for fun Blog.',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <CacheProvider>
          <ChakraProvider>
            {children}
          </ChakraProvider>
        </CacheProvider>
      </body>
    </html>
  );
}
