import React from 'react';
import './globals.css';
import { getRandomPokemonData } from './page';

export const metadata = {
  title: 'Austins for fun Blog.',
  description: 'Generated by create next app',
};

type PokemonForm = {
  name: string;
  url: string;
};

type PokemonInfo = {
  forms: PokemonForm[];
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const randomPokemonData = await getRandomPokemonData();
  const { name } = randomPokemonData.forms[0];
  return (
    <html lang="en">
      <body>

        <h1>{name.toUpperCase()}</h1>
        {children}

      </body>
    </html>
  );
}
