import React from 'react';
import './globals.css';
import Link from 'next/link';

type PokemonForm = {
  name: string;
  url: string;
};

type PokemonSprite = {
  back_default: string;
  front_default: string;
};

type PokemonInfo = {
  forms: PokemonForm[];
  name: string;
  sprites: PokemonSprite;
};

export const pickRandomPokemonNumber = (): number => {
  const min = 1;
  const max = 900;
  return Math.floor(Math.random() * (max - min + 1)) + min;
};

interface RandomPokemonProps {
  number: number;
}

export const getRandomPokemonData = async ({ number }: RandomPokemonProps): Promise<PokemonInfo> => {
  const apiResponse = await fetch(`https://pokeapi.co/api/v2/pokemon/${number}`, { cache: 'no-store' });
  const data = await apiResponse.json();
  return data;
};

export const metadata = {
  title: 'Austins for fun Blog.',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const randomPokemonNumber = pickRandomPokemonNumber();
  return (
    <html lang="en">
      <body>
        <div>
          <ul>
            <li>
              <Link href="/">
                <button type="button"> Home</button>
              </Link>
            </li>
            <li>
              <Link href="/dashboard">
                <button type="button"> To Dashboard</button>
              </Link>
            </li>
            <li>
              <Link href="/orders/1234">
                <button type="button"> To Orders</button>
              </Link>
            </li>
            <li>
              <Link href={`/random-pokemon/${randomPokemonNumber}`}>
                <button type="button"> To a Random Pokemon!</button>
              </Link>
            </li>
          </ul>
        </div>
        {children}

      </body>
    </html>
  );
}
